### ISSUE TITLE
Can't git clone & run

### ISSUE THREAD

**Issue by DeusProx** [gdi2290/ng4-universal-demo#3]
Hello! I wanted to try your project as it looked promising as a starting point for my new project but I couldn't get it running. I encountered the 3 following problems problems:

# Problem 1: Webpack config
The `dist`-variable in `webpack.common.js` is not an absolute path. I required your `helpers.js` and used the `helpers.root` function to solve this.
# Problem 2: @angular/animations not found
I simply installed it & saved it in the `package.json`
# Problem 3: 
```
ERROR in /home/deusprox/git/DeusProx/ng4-universal-demo/src/main.server.aot.ts (10,42): Cannot find module './ngfactory/app/server-app.module.ngfactory'.)
```
Could you plz provide this file?

**Comment by sp90** [comment]
I found a solution working on a PR for all 3

**Comment by sp90** [comment]
@gdi2290 This can be closed i think 👍

**Comment by PatrickJS** [comment]
thanks
