### ISSUE TITLE
Express engine parameter error

### ISSUE THREAD

**Issue by KissBalazs** [gdi2290/ng4-universal-demo#8]
`    ERROR in /home/forestg/projects/ng4-universal-demo/ng4-universal-demo/src/modules/ng-express-engine/express-engine.ts (104,7): Supplied parameters do not match any signature of call target.`

it seems, that the Send() methods parameter has changed. But if I replace

`      callback(null,state.renderToString());`
with
`      callback(state.renderToString());`

the page only renders the javascript code as raw html output. 

without the change, even though the build says there is and error, the app seems to be working just fine.

**Comment by zeves095** [comment]
Only one questuion: 
_grep -ir express-engine ./src/*_ 
has null result... 

what for "express-engine.ts" file - if it not imported from anywhere  ?

**Comment by PatrickJS** [comment]
this should be fixed now
